name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Debug AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY length=${#${{ secrets.AWS_SECRET_ACCESS_KEY }}}"

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

    - name: Copy code to EC2 instances
      env:
        SSH_KEY_PATH: ./private_key
      run: |
        INSTANCE_IDS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=frontend-instance-*" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
        echo "Instance IDs: $INSTANCE_IDS"
        for INSTANCE_ID in $INSTANCE_IDS; do
          echo "Checking instance $INSTANCE_ID"
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "Public IP for instance $INSTANCE_ID: $PUBLIC_IP"
          if [ -z "$PUBLIC_IP" ]; then
            echo "No public IP found for instance $INSTANCE_ID"
            exit 1
          fi
          scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" -r hello-world-frontend ec2-user@$PUBLIC_IP:/home/ec2-user/hello-world-frontend
        done

    - name: Install and run on EC2 instances
      env:
        SSH_KEY_PATH: ./private_key
      run: |
        INSTANCE_IDS=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=frontend-instance-*" "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].InstanceId" --output text)
        echo "Instance IDs: $INSTANCE_IDS"
        for INSTANCE_ID in $INSTANCE_IDS; do
          echo "Checking instance $INSTANCE_ID"
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
          echo "Public IP for instance $INSTANCE_ID: $PUBLIC_IP"
          if [ -z "$PUBLIC_IP" ]; then
            echo "No public IP found for instance $INSTANCE_ID"
            exit 1
          fi
          ssh -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" ec2-user@$PUBLIC_IP "sudo yum update -y && sudo yum install -y nodejs && cd /home/ec2-user/hello-world-frontend && npm install && npm run build && sudo cp -r build/* /usr/share/nginx/html/ && sudo systemctl restart nginx"
        done

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./hello-world-frontend

    - name: Run tests with React
      run: npm test -- --watchAll=false
      working-directory: ./hello-world-frontend