name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory with correct permissions
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add EC2 Instance 1 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_1 }} >> ~/.ssh/known_hosts

      - name: Check environment variables for EC2 Instance 1
        run: |
          echo "HOST=${{ secrets.EC2_FRONTEND_HOST_1 }}"
          echo "USERNAME=${{ secrets.EC2_USER }}"
          echo "KEY length=$(echo -n "${{ secrets.EC2_KEY }}" | wc -c)"

      - name: Verify SSH key permissions and authorized_keys on EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "
            mkdir -p ~/.ssh;
            chmod 700 ~/.ssh;
            touch ~/.ssh/authorized_keys;
            chmod 600 ~/.ssh/authorized_keys;
            echo '$(cat ~/.ssh/authorized_keys)' >> ~/.ssh/authorized_keys;
            cat ~/.ssh/authorized_keys;
            ls -la ~/.ssh;
            sudo tail -n 20 /var/log/auth.log;
          "
          rm key.pem

      - name: Copy code to EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -v -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "echo Connection successful" || exit 1
          rsync -avz -e "ssh -i key.pem" --rsync-path="sudo rsync" hello-world-frontend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }}:/home/${{ secrets.EC2_USER }}/hello-world-frontend/
          rm key.pem

      - name: Add EC2 Instance 2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_2 }} >> ~/.ssh/known_hosts

      - name: Check environment variables for EC2 Instance 2
        run: |
          echo "HOST=${{ secrets.EC2_FRONTEND_HOST_2 }}"
          echo "USERNAME=${{ secrets.EC2_USER }}"
          echo "KEY length=$(echo -n "${{ secrets.EC2_KEY }}" | wc -c)"

      - name: Verify SSH key permissions and authorized_keys on EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "
            mkdir -p ~/.ssh;
            chmod 700 ~/.ssh;
            touch ~/.ssh/authorized_keys;
            chmod 600 ~/.ssh/authorized_keys;
            echo '$(cat ~/.ssh/authorized_keys)' >> ~/.ssh/authorized_keys;
            cat ~/.ssh/authorized_keys;
            ls -la ~/.ssh;
            sudo tail -n 20 /var/log/auth.log;
          "
          rm key.pem

      - name: Copy code to EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -v -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "echo Connection successful" || exit 1
          rsync -avz -e "ssh -i key.pem" --rsync-path="sudo rsync" hello-world-frontend/ ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }}:/home/${{ secrets.EC2_USER }}/hello-world-frontend/
          rm key.pem

  test:
    runs-on: ubuntu-latest
    needs: copy

    steps:
      - name: Create .ssh directory with correct permissions
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add EC2 Instance 1 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_1 }} >> ~/.ssh/known_hosts

      - name: Test on EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "sudo yum install -y nodejs"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "mkdir -p /home/${{ secrets.EC2_USER }}/hello-world-frontend"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "cd /home/${{ secrets.EC2_USER }}/hello-world-frontend && npm install"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "cd /home/${{ secrets.EC2_USER }}/hello-world-frontend && npm test -- --watchAll=false"
          rm key.pem

      - name: Add EC2 Instance 2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_2 }} >> ~/.ssh/known_hosts

      - name: Test on EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "sudo yum install -y nodejs"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "mkdir -p /home/${{ secrets.EC2_USER }}/hello-world-frontend"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "cd /home/${{ secrets.EC2_USER }}/hello-world-frontend && npm install"
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "cd /home/${{ secrets.EC2_USER }}/hello-world-frontend && npm test -- --watchAll=false"
          rm key.pem

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Create .ssh directory with correct permissions
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add EC2 Instance 1 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_1 }} >> ~/.ssh/known_hosts

      - name: Build on EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "cd /home/${{ secrets.EC2_USER }}/hello-world-frontend && npm run build"
          rm key.pem

      - name: Add EC2 Instance 2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_2 }} >> ~/.ssh/known_hosts

      - name: Build on EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "cd /home/${{ secrets.EC2_USER }}/hello-world-frontend && npm run build"
          rm key.pem

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create .ssh directory with correct permissions
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add EC2 Instance 1 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_1 }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 Instance 1
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_1 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_1 }} "sudo cp -r /home/${{ secrets.EC2_USER }}/hello-world-frontend/build/* /usr/share/nginx/html/ && sudo systemctl restart nginx"
          rm key.pem

      - name: Add EC2 Instance 2 to known_hosts
        run: ssh-keyscan -H ${{ secrets.EC2_FRONTEND_HOST_2 }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 Instance 2
        env:
          HOST: ${{ secrets.EC2_FRONTEND_HOST_2 }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_FRONTEND_HOST_2 }} "sudo cp -r /home/${{ secrets.EC2_USER }}/hello-world-frontend/build/* /usr/share/nginx/html/ && sudo systemctl restart nginx"
          rm key.pem
